### ISSUE TITLE
Scalatra application will not run in IntelliJ 2017.1 with Jetty Runner 

### ISSUE THREAD

**Issue by michael-card** [guikeller/jetty-runner#35]
I have been running Scalatra apps with Jetty Runner for some time now, and when I upgraded from IntelliJ 2016.3 to 2017.1 all of sudden my Scalatra apps ceased to work. When you try to run them, they crash with the following stack trace, even on a "hello world" Scalatra app that does nothing:

~~~~
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at org.fusesource.scalate.TemplateEngine.<init>(TemplateEngine.scala:181)
	at org.fusesource.scalate.servlet.ServletTemplateEngine.<init>(ServletTemplateEngine.scala:95)
	at org.scalatra.scalate.ScalateSupport$$anonfun$createTemplateEngine$1$$anon$1.<init>(ScalateSupport.scala:90)
	at org.scalatra.scalate.ScalateSupport$$anonfun$createTemplateEngine$1.apply(ScalateSupport.scala:90)
	at org.scalatra.scalate.ScalateSupport$$anonfun$createTemplateEngine$1.apply(ScalateSupport.scala:90)
	at org.scalatra.scalate.ScalateSupport$$anonfun$scalateTemplateEngine$1.apply(ScalateSupport.scala:37)
	at org.scalatra.scalate.ScalateSupport$$anonfun$scalateTemplateEngine$1.apply(ScalateSupport.scala:36)
	at scala.Option.getOrElse(Option.scala:120)
	at org.scalatra.scalate.ScalateSupport$.scalateTemplateEngine(ScalateSupport.scala:36)
	at org.scalatra.scalate.ScalateSupport$class.createTemplateEngine(ScalateSupport.scala:90)
	at com.dandb.application_services.ApplicationServicesServlet.createTemplateEngine(ApplicationServicesServlet.scala:5)
	at org.scalatra.scalate.ScalateSupport$class.initialize(ScalateSupport.scala:61)
	at com.dandb.application_services.ApplicationServicesServlet.initialize(ApplicationServicesServlet.scala:5)
	at com.dandb.application_services.ApplicationServicesServlet.initialize(ApplicationServicesServlet.scala:5)
	at org.scalatra.ScalatraServlet$class.init(ScalatraServlet.scala:124)
	at com.dandb.application_services.ApplicationServicesServlet.init(ApplicationServicesServlet.scala:5)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:640)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:419)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:875)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:411)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:378)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:495)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:536)
~~~~

The problem seems to be a version dependency or similar error involving Scalate. Now the interesting thing is that if you just run sbt and do a jetty:start the application runs fine and there are no errors. If there is a work-around for this I would sure appreciate it.

I have also posted to the Scalatra group if this turns out to be a Scalatra bug I will come back and close this issue, thanks!

**Comment by guikeller** [comment]
Hi @michael-card 

It seems that the root cause is with one of your Scala dependencies:
[b]NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;[/b]

http://stackoverflow.com/questions/25089852/what-is-the-reason-for-java-lang-nosuchmethoderror-scala-predef-arrowassoc-upo

http://stackoverflow.com/questions/18345085/java-lang-nosuchmethoderror-in-scalatra-using-scalate-with-markdown

You can generate your dependency tree by running:
$ [i]sbt inspect tree clean[i]

Let me know how you go :) 👍

**Comment by guikeller** [comment]
Hi @michael-card,

Sorry for taking so long to come back to you! 😞 
I was on holidays (and still) with limited access to internet; but let's do this!

Somewhere in the _logs that you sent_ to my email I found this:
> 
> inspect tree clean
> .... (reduced for brevity)
> [info]       | +-*:libraryDependencies =3D List(org.scala-lang:scala-library:2.12.1, *org.eclipse.jetty:jetty-runner:9.2.1.v20140609:jetty*, org.eclipse.jetty:jetty-runner:..
> [info]       | | +-*/*:au .... (reduced for brevity)
> [info]       +-*:ivyConfigurations =3D List(compile, runtime, test, provided, optional, container, jetty, compile-internal, runtime-internal, test-internal, plugin, sourc.
>
Meaning that one of your dependencies is including **Jetty Runner 9.2.1** to the classpath and causing the plugin to go pear shaped as it runs on top of _**Jetty Runner 9.3.11**_

So, that looks like a classpath issue to me and if you **remove** that reference to **Jetty Runner 9.2.1** from your **classpath** tree the plugin should be all go. 😃 

Let me know how you go after the changes!
All the best on your project 👍 

Cheers,
Gui

**Comment by guikeller** [comment]
Closing the issue after 5 days have passed, feel free to re-open it if needed.

**Comment by michael-card** [comment]
OK @guikeller I haven't tested the 2017.1.1 release of IntelliJ that might fix this, when I do I will come back here and let you know my results

**Comment by michael-card** [comment]
No joy. I see this dependency as well but I have NO IDEA where it comes from and apparently no way of finding out. I went through every file in the library and did a tvf and came up with nothing. I dod not see how that is in there

**Comment by guikeller** [comment]
Hi @michael-card,

The dependency gets added to the classpath (or at least seems to) by the xsbt-web-plugin from what I have found.

Have a look on "your_project/plugins.sbt" for it and look for how you can upgrade the jetty-runner to match the same version (9.3.11) used by the IDEA Jetty Runner plugin.

I haven't worked with Scala just yet, so my knowledge is limited on SBT and its dependency management resolution / overrides / excludes.

Best of luck! :thumbup:
Cheers, Gui

**Comment by michael-card** [comment]
Hey thanks GUI I will look at this tonight. Absolutely bizarre that this happens and doesn't effect the 2016.3 build of idea!

-Mike

Sent from my iPhone

On May 2, 2017, at 5:32 PM, Gui Keller <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @michael-card<https://github.com/michael-card>,

The dependency gets added to the classpath (or at least seems to) by the xsbt-web-plugin from what I have found.

Have a look on "your_project/plugins.sbt" for it and look for how you can upgrade the jetty-runner to match the same version (9.3.11) used by the IDEA Jetty Runner plugin.

I haven't worked with Scala just yet, so my knowledge is limited on SBT and its dependency management resolution / overrides / excludes.

Best of luck! :thumbup:
Cheers, Gui

**Comment by michael-card** [comment]
Hey Gui-

I never import that plug in. This is what is in my plugins.sbt


addSbtPlugin("org.scalatra.scalate" % "sbt-scalate-precompiler" % "1.8.0.1")

addSbtPlugin("org.scalatra.sbt" % "scalatra-sbt" % "0.5.1")

addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.2.0-M9”)

[cid:image013.png@01D27338.EABB9350]

Michael Card
Senior Software Engineer
7700 Parmer Lane, Building A
Austin, TX 78729
Mobile 315.200.7043

dnb.com<http://www.dnb.com/>


[cid:image014.png@01D27338.EABB9350]<http://www.facebook.com/DunBradstreet>[cid:image015.png@01D27338.EABB9350]<http://twitter.com/dnbus>[cid:image016.png@01D27338.EABB9350]<http://www.linkedin.com/company/dun-&-bradstreet>[cid:image017.png@01D27338.EABB9350]<http://www.youtube.com/user/DunandBrad>

From: Michael Card <cardm@dnb.com<mailto:cardm@dnb.com>>
Date: Tuesday, May 2, 2017 at 5:37 PM
To: guikeller/jetty-runner <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: Re: [guikeller/jetty-runner] Scalatra application will not run in IntelliJ 2017.1 with Jetty Runner (#35)

Hey thanks GUI I will look at this tonight. Absolutely bizarre that this happens and doesn't effect the 2016.3 build of idea!

-Mike

Sent from my iPhone

On May 2, 2017, at 5:32 PM, Gui Keller <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @michael-card<https://github.com/michael-card>,

The dependency gets added to the classpath (or at least seems to) by the xsbt-web-plugin from what I have found.

Have a look on "your_project/plugins.sbt" for it and look for how you can upgrade the jetty-runner to match the same version (9.3.11) used by the IDEA Jetty Runner plugin.

I haven't worked with Scala just yet, so my knowledge is limited on SBT and its dependency management resolution / overrides / excludes.

Best of luck! :thumbup:
Cheers, Gui

**Comment by guikeller** [comment]
Hi @michael-card, 

From what I can see from your _plugins.sbt_ you are using:
`addSbtPlugin("org.scalatra.sbt" % "scalatra-sbt" % "0.5.1")`

Here is what its project page says about it:
> It depends on xsbt-web-plugin so you don't need to specify that explicitly.
Source: https://github.com/scalatra/scalatra-sbt

The Pretty Solution:
Explicitly add the xsbt-web-plugin and configure to use a specific jetty-version
https://github.com/earldouglas/xsbt-web-plugin#jetty-version

The Ugly Solution:
Find and delete your current "Jetty Runner JAR 9.2.1"
Put the "Jetty Runner JAR 9.3.11" in place and rename it to "Jetty Runner JAR 9.2.1"

Hope this helps you get going.
Let me know how you go with that.

Cheers,
Gui

**Comment by michael-card** [comment]
Hey Gui I want to thank you so much for your help on this. There is no way to get a 2017.* version of IntelliJ running, tried modifying my build.sbt to be like this:


enablePlugins(JettyPlugin)
enablePlugins(JavaAppPackaging)
enablePlugins(DockerPlugin)

containerLibs in Jetty := Seq("org.eclipse.jetty" % "jetty-runner" % "9.2.1.v20140609" intransitive())

Total fail, still get bad results:

java.lang.NoSuchMethodError: scala.runtime.BooleanRef.create(Z)Lscala/runtime/BooleanRef;

I had installed version 9.2.1 of the Jetty-Runner plug-in by downloading it manually too, but all to no avail. The bottom line seems to be that IntelliJ 2017.* is not compatible with that version of the Jetty-Runner plugin, so the Scalatra folks will have to fix their jar or an upgrade to 2017.* is not possible.

-Mike

[cid:image013.png@01D27338.EABB9350]

Michael Card
Senior Software Engineer
7700 Parmer Lane, Building A
Austin, TX 78729
Mobile 315.200.7043

dnb.com<http://www.dnb.com/>


[cid:image014.png@01D27338.EABB9350]<http://www.facebook.com/DunBradstreet>[cid:image015.png@01D27338.EABB9350]<http://twitter.com/dnbus>[cid:image016.png@01D27338.EABB9350]<http://www.linkedin.com/company/dun-&-bradstreet>[cid:image017.png@01D27338.EABB9350]<http://www.youtube.com/user/DunandBrad>

**Comment by guikeller** [comment]
Hi @michael-card ,

No worries, I am glad to help the way I can!
I hope we can get you back using the plugin..

So, if you did not manage to get it going with the "**Pretty Solution**", I suggest for you to use the "**Ugly Solution**", to get you going for now.  Also, raise a bug with the guys from Scalatra they should work on a fix so you can specify the version of jetty runner that you want to use 😉 

**The Ugly Solution**:
1) Close your JetBrains IntelliJ IDEA
2) Find "_jetty-runner-9.2.1.jar_" on your sbt / ivy repository
3) Copy the "_jetty-runner-9.3.11.jar_" into the "_jetty-runner-9.2.1.jar_" directory
4) Rename the "_jetty-runner-9.2.1.jar_" to "_BKP_jetty-runner-9.2.1.jar_"
5) Rename the "_jetty-runner-9.3.11.jar_" to "_jetty-runner-9.2.1.jar_"
6) Use the IDEA Jetty-Runner plugin as you did before

If that doesn't work you will have to wait for the guys from Scalatra to fix the bug / implement this feature for you. Good luck with that! 👍 

Best regards,
Gui
